In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv('/content/ecommerce_messy_dataset.csv')

In [ ]:
data

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,NaN,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,kolkata,Clothing,Lipstick,3033.43,2.0,NaN
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,NaN,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
4,NaN,2023-05-04,CUST1532,Female,39.0,kolkata,Beauty,Dress,376.42,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,M,34.0,Hyderabad,NaN,Dress,401.43,5.0,UPI
5196,ORD13297,2022-02-26,CUST1554,NaN,19.0,Hyderabad,NaN,Headphones,2897.86,5.0,Debit Card
5197,ORD14756,2023-09-12,CUST1566,M,55.0,NaN,Home,Laptop,2156.39,1.0,NaN
5198,ORD13192,2022-03-09,CUST1019,NaN,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card

In [ ]:
data['Age'].mean()

np.float64(38.34764624778413)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5084 non-null   object
 1   Order_Date        4957 non-null   object
 2   Customer_ID       5140 non-null   object
 3   Gender            4311 non-null   object
 4   Age               5077 non-null   float64
 5   City              4567 non-null   object
 6   Product_Category  4316 non-null   object
 7   Product_Name      4497 non-null   object
 8   Price             5051 non-null   float64
 9   Quantity          4318 non-null   float64
 10  Payment_Method    4192 non-null   object
dtypes: float64(3), object(8)
memory usage: 447.0+ KB

In [ ]:
data.isnull().sum()

Order_ID             116
Order_Date           243
Customer_ID           60
Gender               889
Age                  123
City                 633
Product_Category     884
Product_Name         703
Price                149
Quantity             882
Payment_Method      1008
dtype: int64

In [ ]:
data.describe()

               Age        Price     Quantity
count  5077.000000  5051.000000  4318.000000
mean     38.347646  2560.201924     2.997453
std      11.950692  1418.007295     1.430740
min      18.000000   100.060000     1.000000
25%      28.000000  1337.260000     2.000000
50%      38.000000  2578.850000     3.000000
75%      48.000000  3786.705000     4.000000
max      59.000000  4999.260000     5.000000

In [ ]:
data=data.dropna(subset=['Order_ID'])

add a extra data for update the actual data permanently ..dropna use for remove null values

In [ ]:
data

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,NaN,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,kolkata,Clothing,Lipstick,3033.43,2.0,NaN
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,NaN,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
5,ORD10005,2022-09-18,CUST1266,Other,47.0,NaN,Beauty,Dress,1140.46,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,M,34.0,Hyderabad,NaN,Dress,401.43,5.0,UPI
5196,ORD13297,2022-02-26,CUST1554,NaN,19.0,Hyderabad,NaN,Headphones,2897.86,5.0,Debit Card
5197,ORD14756,2023-09-12,CUST1566,M,55.0,NaN,Home,Laptop,2156.39,1.0,NaN
5198,ORD13192,2022-03-09,CUST1019,NaN,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card

In [ ]:
categorical={'Gender','City','Product_Category','Product_Name','Payment_Method'}
for i in categorical:
  data[i].fillna("unkown",inplace=True)

/tmp/ipykernel_1087/3437043769.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[i].fillna("unkown",inplace=True)
/tmp/ipykernel_1087/3437043769.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[i].fillna("unkown",inplace=True)

where fillna use for replace and inplace=true use for permanently save the data

In [ ]:
data.isnull().sum()

Order_ID              0
Order_Date          230
Customer_ID          60
Gender                0
Age                 123
City                  0
Product_Category      0
Product_Name          0
Price               146
Quantity            863
Payment_Method        0
dtype: int64

In [ ]:
numarical={'Age','Price','Quantity'}
for i in numarical:
  data[i].fillna(data[i].median(),inplace=True)

/tmp/ipykernel_1087/354622258.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[i].fillna(data[i].median(),inplace=True)
/tmp/ipykernel_1087/354622258.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[i].fillna(data[i].median(),inplace=True)

In [ ]:
data.isnull().sum()

Order_ID              0
Order_Date          230
Customer_ID          60
Gender                0
Age                   0
City                  0
Product_Category      0
Product_Name          0
Price                 0
Quantity              0
Payment_Method        0
dtype: int64

In [ ]:

data=data.dropna(subset=['Customer_ID'])

In [ ]:
data["Gender"].unique()

array(['Female', 'Male', 'Other', 'M', 'unkown', 'F'], dtype=object)

In [ ]:
data['Gender']=data['Gender'].replace({'M':'Male','F':'Female'})

/tmp/ipykernel_1087/1008324566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Gender']=data['Gender'].replace({'M':'Male','F':'Female'})

In [ ]:
data['City'].unique()

array(['Delhi', 'kolkata', 'Mumbai', 'Hyderabad', 'unkown', 'Kolkata',
       'Bangalore', 'Chennai'], dtype=object)

In [ ]:
data

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,unkown,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,kolkata,Clothing,Lipstick,3033.43,2.0,unkown
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,unkown,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
5,ORD10005,2022-09-18,CUST1266,Other,47.0,unkown,Beauty,Dress,1140.46,4.0,unkown
...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,Male,34.0,Hyderabad,unkown,Dress,401.43,5.0,UPI
5196,ORD13297,2022-02-26,CUST1554,unkown,19.0,Hyderabad,unkown,Headphones,2897.86,5.0,Debit Card
5197,ORD14756,2023-09-12,CUST1566,Male,55.0,unkown,Home,Laptop,2156.39,1.0,unkown
5198,ORD13192,2022-03-09,CUST1019,unkown,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card

In [ ]:
#str for string method and str.title change the small k kolkata to cap k kolkata... title use for implementing in hole column


data['City']=data['City'].str.title()

/tmp/ipykernel_1087/4024227141.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['City']=data['City'].str.title()

In [ ]:
data['City'].unique()

array(['Delhi', 'Kolkata', 'Mumbai', 'Hyderabad', 'Unkown', 'Bangalore',
       'Chennai'], dtype=object)

In [ ]:
data['Payment_Method'].unique()

array(['Cash', 'unkown', 'Credit Card', 'UPI', 'Debit Card'], dtype=object)

In [ ]:

data['Order_Date']=pd.to_datetime(data['Order_Date'])

/tmp/ipykernel_1087/1578113813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Order_Date']=pd.to_datetime(data['Order_Date'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5024 entries, 0 to 5199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5024 non-null   object
 1   Order_Date        4798 non-null   datetime64[ns]
 2   Customer_ID       5024 non-null   object
 3   Gender            5024 non-null   object
 4   Age               5024 non-null   float64
 5   City              5024 non-null   object
 6   Product_Category  5024 non-null   object
 7   Product_Name      5024 non-null   object
 8   Price             5024 non-null   float64
 9   Quantity          5024 non-null   float64
 10  Payment_Method    5024 non-null   object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 600.0+ KB

In [ ]:
#ffill use for forward data fill...(replaced by forward data)   bfill use for replace with backward data
data['Order_Date'].fillna(method='ffill',inplace=True)

/tmp/ipykernel_1087/3110128183.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Order_Date'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_1087/3110128183.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Order_Date'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_1087/3110128183.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Order_Date'].fillna(method='ffill',inplace=True)

In [ ]:
data.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Gender              0
Age                 0
City                0
Product_Category    0
Product_Name        0
Price               0
Quantity            0
Payment_Method      0
dtype: int64

In [ ]:
data

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,unkown,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,Kolkata,Clothing,Lipstick,3033.43,2.0,unkown
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,unkown,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
5,ORD10005,2022-09-18,CUST1266,Other,47.0,Unkown,Beauty,Dress,1140.46,4.0,unkown
...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,Male,34.0,Hyderabad,unkown,Dress,401.43,5.0,UPI
5196,ORD13297,2022-02-26,CUST1554,unkown,19.0,Hyderabad,unkown,Headphones,2897.86,5.0,Debit Card
5197,ORD14756,2023-09-12,CUST1566,Male,55.0,Unkown,Home,Laptop,2156.39,1.0,unkown
5198,ORD13192,2022-03-09,CUST1019,unkown,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5024 entries, 0 to 5199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5024 non-null   object
 1   Order_Date        5024 non-null   datetime64[ns]
 2   Customer_ID       5024 non-null   object
 3   Gender            5024 non-null   object
 4   Age               5024 non-null   float64
 5   City              5024 non-null   object
 6   Product_Category  5024 non-null   object
 7   Product_Name      5024 non-null   object
 8   Price             5024 non-null   float64
 9   Quantity          5024 non-null   float64
 10  Payment_Method    5024 non-null   object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 600.0+ KB

In [ ]:
data['total']=data['Price']*data['Quantity']

/tmp/ipykernel_1087/2323157951.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['total']=data['Price']*data['Quantity']

In [ ]:
data.head()

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method,total
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,unkown,4003.06,3.0,Cash,12009.18
1,ORD10001,2022-03-03,CUST1761,Male,25.0,Kolkata,Clothing,Lipstick,3033.43,2.0,unkown,6066.86
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,unkown,Lipstick,589.88,3.0,Cash,1769.64
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash,5205.51
5,ORD10005,2022-09-18,CUST1266,Other,47.0,Unkown,Beauty,Dress,1140.46,4.0,unkown,4561.84

In [ ]:
data['Month']=data['Order_Date'].dt.month

/tmp/ipykernel_1087/3332141714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Month']=data['Order_Date'].dt.month

In [ ]:
data

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method,total,Month
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,unkown,4003.06,3.0,Cash,12009.18,1
1,ORD10001,2022-03-03,CUST1761,Male,25.0,Kolkata,Clothing,Lipstick,3033.43,2.0,unkown,6066.86,3
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,unkown,Lipstick,589.88,3.0,Cash,1769.64,9
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash,5205.51,3
5,ORD10005,2022-09-18,CUST1266,Other,47.0,Unkown,Beauty,Dress,1140.46,4.0,unkown,4561.84,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,Male,34.0,Hyderabad,unkown,Dress,401.43,5.0,UPI,2007.15,1
5196,ORD13297,2022-02-26,CUST1554,unkown,19.0,Hyderabad,unkown,Headphones,2897.86,5.0,Debit Card,14489.30,2
5197,ORD14756,2023-09-12,CUST1566,Male,55.0,Unkown,Home,Laptop,2156.39,1.0,unkown,2156.39,9
5198,ORD13192,2022-03-09,CUST1019,unkown,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card,24760.45,3
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card,10700.76,5

In [ ]:
data['Month'].unique()

array([ 1,  3,  9,  7,  4,  2,  8, 11, 10,  5,  6, 12], dtype=int32)

In [ ]:
data['Month'].mode()

0    4
Name: Month, dtype: int32

In [ ]:
data['Product_Category'].unique()

array(['Clothing', 'unkown', 'Sports', 'Beauty', 'Home', 'Electronics'],
      dtype=object)

In [ ]:
#higest sell of chategory?(sports)
data.groupby('Product_Category')['Quantity'].sum()

Product_Category
Beauty         2423.0
Clothing       2442.0
Electronics    2501.0
Home           2515.0
Sports         2598.0
unkown         2560.0
Name: Quantity, dtype: float64

In [ ]:
#higest revenew of chategory?(Electronics)
data.groupby('Product_Category')['total'].sum()

Product_Category
Beauty         6441325.48
Clothing       6239845.53
Electronics    6565865.34
Home           6303178.38
Sports         6404116.86
unkown         6487862.51
Name: total, dtype: float64

In [ ]:
#which product has the higest sell? (sofa)
data.groupby('Product_Name')['Quantity'].sum()

Product_Name
Dress         1818.0
Football      1877.0
Headphones    1861.0
Laptop        1794.0
Lipstick      1888.0
Shirt         1775.0
Sofa          2027.0
unkown        1999.0
Name: Quantity, dtype: float64

In [ ]:
#higest revenew of ?(sofa)
data.groupby('Product_Name')['total'].sum()

Product_Name
Dress         4544840.68
Football      4935342.65
Headphones    4833207.37
Laptop        4517612.07
Lipstick      4816831.18
Shirt         4629641.35
Sofa          5115745.44
unkown        5048973.36
Name: total, dtype: float64

In [ ]:
#which month has the higst revenew? (4)
data.groupby('Month')['total'].sum()

Month
1     3639458.87
2     3101889.35
3     3339396.16
4     3682679.88
5     3519158.97
6     3419708.58
7     3589247.75
8     3558569.33
9     3329947.83
10    2451829.89
11    2357696.12
12    2452611.37
Name: total, dtype: float64

In [ ]:
#which month has the highst amount of sell? (5)
data.groupby('Month')['Quantity'].sum()

Month
1     1396.0
2     1235.0
3     1300.0
4     1438.0
5     1454.0
6     1300.0
7     1434.0
8     1401.0
9     1251.0
10     919.0
11     912.0
12     999.0
Name: Quantity, dtype: float64

In [ ]:
#which city has the higest revenew or total?(kolkata)

data.groupby('City')['Quantity'].sum()

City
Bangalore    1810.0
Chennai      2049.0
Delhi        1828.0
Hyderabad    1823.0
Kolkata      3800.0
Mumbai       1906.0
Unkown       1823.0
Name: Quantity, dtype: float64